# Generated by Django 5.1.1 on 2024-09-21 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weathersearchhistory',
            old_name='weather_description',
            new_name='wind_direction',
        ),
    ]
