# Generated by Django 5.1.1 on 2024-09-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_rename_weather_description_weathersearchhistory_wind_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathersearchhistory',
            name='search_time',
            field=models.DateTimeField(),
        ),
    ]
