# Generated by Django 5.1.1 on 2024-09-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_weathersearchhistory_search_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathersearchhistory',
            name='search_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
